version: '3.7'

networks:
  forum:

services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: forum-app
    env_file: ./.env
    ports:
      - 8888:8888
      - 9230:9229
    volumes:
      - .:/usr/app
    environment:
      - POSTGRES_HOST=$DB_DOCKER_HOST
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_BASE
      - POSTGRES_PORT=$DB_DOCKER_PORT
    command: yarn dev --inspect-brk=0.0.0.0:9229
    links:
      - database
    depends_on:
      - database
    networks:
      - forum

  database:
    image: postgres:alpine
    container_name: forum-database
    restart: always
    env_file: ./.env
    ports:
      - $DB_LOCAL_PORT:$DB_DOCKER_PORT
    environment:
      - POSTGRES_HOST=$DB_DOCKER_HOST
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - POSTGRES_DB=$DB_BASE
      - POSTGRES_PORT=$DB_DOCKER_PORT
    expose:
      - POSTGRES_PORT=$DB_DOCKER_PORT
    volumes:
      - .docker/dbdata:/var/lib/postgresql
    networks:
      - forum